# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'factory_bot', '~> 4.8'
gem 'httparty', '~> 0.17.0'
gem 'json', '~> 2.5.0'
gem 'rake', '~> 13.0.0'
gem 'rspec', '~> 3.10.0'
gem 'rubocop', '~> 1.16.0'
gem 'uri', '~> 0.10.0'
